-- DROP USER ORAMAN;

-- CREATE USER ORAMAN
-- IDENTIFIED BY <password>
-- ;

CREATE TABLE "ORAMAN"."BOARDS" 
   (	"NO" NUMBER(38,0) NOT NULL ENABLE, 
	"WRITER" VARCHAR2(30), 
	"PASSWORD" VARCHAR2(50), 
	"SUBJECT" VARCHAR2(50), 
	"CONTENT" VARCHAR2(255), 
	"READHIT" NUMBER(38,0) DEFAULT 0, 
	"REGDATE" DATE DEFAULT sysdate, 
	 CONSTRAINT "boards_no_pk" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE ORAMAN.BOARDS IS '게시물을 위한 테이블입니다.';
COMMENT ON COLUMN ORAMAN.BOARDS."NO" IS '게시물 글번호이며, 기본 키입니다.';
COMMENT ON COLUMN ORAMAN.BOARDS.WRITER IS '회원의 아이디이며 외래키입니다.';
COMMENT ON COLUMN ORAMAN.BOARDS.PASSWORD IS '게시물 관련 비밀 번호입니다.';
COMMENT ON COLUMN ORAMAN.BOARDS.SUBJECT IS '게시물의 글 제목입니다.';
COMMENT ON COLUMN ORAMAN.BOARDS.CONTENT IS '게시물의 글 내용입니다.';
COMMENT ON COLUMN ORAMAN.BOARDS.READHIT IS '게시물의 조회수입니다.
boards_readhit_ck, readhit >= 0';
COMMENT ON COLUMN ORAMAN.BOARDS.REGDATE IS '게시물이 작성된 일자입니다.';

CREATE TABLE "ORAMAN"."MEMBERS" 
   (	"ID" VARCHAR2(30) NOT NULL ENABLE, 
	"NAME" VARCHAR2(30), 
	"PASSWORD" VARCHAR2(30), 
	"GENDER" VARCHAR2(6), 
	"BIRTH" DATE DEFAULT sysdate, 
	"MARRIAGE" VARCHAR2(30) DEFAULT '미혼' NOT NULL ENABLE, 
	"SALARY" NUMBER(10,2) DEFAULT 0, 
	"ADDRESS" VARCHAR2(255), 
	"MANAGER" VARCHAR2(50), 
	 CONSTRAINT "MEMBERS_id_pk" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE ORAMAN.MEMBERS IS '회원을 위한 테이블입니다.';
COMMENT ON COLUMN ORAMAN.MEMBERS.ID IS '회원의 아이디입니다.';

CREATE TABLE "ORAMAN"."ORDERDETAILS" 
   (	"ODID" NUMBER(38,0) NOT NULL ENABLE, 
	"OID" NUMBER(38,0) NOT NULL ENABLE, 
	"PNUM" NUMBER(38,0), 
	"QTY" NUMBER(38,0) DEFAULT 0, 
	 CONSTRAINT "ORDERDETAILS_ODID_PK" PRIMARY KEY ("ODID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE ORAMAN.ORDERDETAILS IS '주문을 위한 테이블입니다.';
COMMENT ON COLUMN ORAMAN.ORDERDETAILS.ODID IS '주문 상세를 위한 기본 키입니다.';
COMMENT ON COLUMN ORAMAN.ORDERDETAILS."OID" IS '주문(송장) 번호이며, 주문 테이블의 oid 컬럼에 대한 외래 키 입니다.
(on delete set null)';
COMMENT ON COLUMN ORAMAN.ORDERDETAILS.PNUM IS '상품 번호를 의미하며, 상품 테이블의 num 컬럼에 대한 외래 키입니다.
(on delete set null)';
COMMENT ON COLUMN ORAMAN.ORDERDETAILS.QTY IS '해당 상품의 주문 수량을 의미합니다.';

CREATE TABLE "ORAMAN"."ORDERS" 
   (	"OID" NUMBER(38,0) NOT NULL ENABLE, 
	"MID" VARCHAR2(10), 
	"ORDERDATE" DATE DEFAULT sysdate, 
	 CONSTRAINT "ORDERS_OID_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE ORAMAN.ORDERS IS '주문을 위한 테이블입니다.';
COMMENT ON COLUMN ORAMAN.ORDERS."OID" IS '주문(송장) 번호이며, 기본 키 입니다';
COMMENT ON COLUMN ORAMAN.ORDERS.MID IS '회원 아이디를 의미합니다.';
COMMENT ON COLUMN ORAMAN.ORDERS.ORDERDATE IS '주문한 날짜입니다';

CREATE TABLE "ORAMAN"."PRODUCTS" 
   (	"NUM" NUMBER(38,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"COMPANY" VARCHAR2(50), 
	"IMAGE" VARCHAR2(30), 
	"STOCK" NUMBER(38,0) DEFAULT 0, 
	"PRICE" NUMBER(38,0) DEFAULT 0, 
	"CATEGORY" VARCHAR2(12), 
	"CONTENT" VARCHAR2(300), 
	"POINT" NUMBER(38,0) DEFAULT 5, 
	"INPUTDATE" DATE DEFAULT sysdate, 
	 CONSTRAINT "products_num_pk" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE ORAMAN.PRODUCTS IS '상품을 위한 테이블입니다.';
COMMENT ON COLUMN ORAMAN.PRODUCTS.NUM IS '상품 번호를 의미하며, 기본 키(products_num_pk)입니다.';
COMMENT ON COLUMN ORAMAN.PRODUCTS.NAME IS '상품의 이름입니다.';
COMMENT ON COLUMN ORAMAN.PRODUCTS.COMPANY IS '상품의 제조 회사(거래처 이름)입니다.';
COMMENT ON COLUMN ORAMAN.PRODUCTS.IMAGE IS '상품에 사용할 이미지 파일 이름입니다.';
COMMENT ON COLUMN ORAMAN.PRODUCTS.STOCK IS '상품의 재고 수량(products_stock_ck, stock>=0)입니다.';
COMMENT ON COLUMN ORAMAN.PRODUCTS.PRICE IS '상품의 단가(products_price_ck, price>=0)입니다.';
COMMENT ON COLUMN ORAMAN.PRODUCTS.CATEGORY IS '상품에 대한 카테고리(products_category_ck)입니다.
category in(''bread'', ''beverage'', ''cake'', ''macaron'')';
COMMENT ON COLUMN ORAMAN.PRODUCTS.CONTENT IS '상품에 대한 상세 설명입니다.';
COMMENT ON COLUMN ORAMAN.PRODUCTS.POINT IS '상품 구매시 적립할 포인트(products_point_ck, point>=0)입니다.';
COMMENT ON COLUMN ORAMAN.PRODUCTS.INPUTDATE IS '상품의 입고 일자입니다.';

CREATE SEQUENCE ORAMAN.BOARD_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 1000000 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE ORAMAN.ORDERDETAIL_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE ORAMAN.ORDER_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE ORAMAN.PRODUCT_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;