-- 테이블 생성
-- MEMBERS
CREATE TABLE MEMBERS (
    ID VARCHAR2(30),
    NAME VARCHAR2(30),
    PASSWORD VARCHAR2(30),
    GENDER VARCHAR2(6),
    BIRTH DATE DEFAULT SYSDATE,
    MARRIAGE VARCHAR2(30) DEFAULT '미혼' NOT NULL,
    SALARY NUMBER(10,2) DEFAULT 0,
    ADDRESS VARCHAR2(255),
    MANAGER VARCHAR2(50)
);

-- BOARDS
CREATE TABLE BOARDS (
    NO NUMBER,
    WRITER VARCHAR2(30),
    PASSWORD VARCHAR2(50),
    SUBJECT VARCHAR2(50),
    CONTENT VARCHAR2(255),
    READHIT NUMBER DEFAULT 0,
    REGDATE DATE DEFAULT SYSDATE
);

-- PRODUCTS
CREATE TABLE PRODUCTS (
    NUM NUMBER,
    NAME VARCHAR2(50) NOT NULL,
    COMPANY VARCHAR2(50),
    IMAGE VARCHAR2(30),
    STOCK NUMBER DEFAULT 0,
    PRICE NUMBER DEFAULT 0,
    CATEGORY VARCHAR2(12),
    CONTENT VARCHAR2(300),
    POINT NUMBER DEFAULT 5,
    INPUTDATE DATE DEFAULT SYSDATE
);

-- ORDERS
CREATE TABLE ORDERS (
    OID NUMBER,
    MID VARCHAR2(10),
    ORDERDATE DATE DEFAULT SYSDATE
);

-- ORDERDETAILS
CREATE TABLE ORDERDETAILS (
    ODID NUMBER,
    OID NUMBER NOT NULL,
    PNUM NUMBER,
    QTY NUMBER DEFAULT 0
);


-- 제약 조건 (ALTER TABLE)
-- MEMBERS 제약 조건
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PK PRIMARY KEY (ID);
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PASSWORD_CK CHECK (LENGTH(PASSWORD) BETWEEN 3 AND 50);
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_GENDER_CK CHECK (GENDER IN ('남자','여자'));
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_MARRIAGE_CK CHECK (MARRIAGE IN ('결혼','이혼','미혼'));
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_SALARY_CK CHECK (SALARY >= 100);

-- BOARDS 제약 조건
ALTER TABLE BOARDS ADD CONSTRAINT BOARDS_PK PRIMARY KEY (NO);
ALTER TABLE BOARDS ADD CONSTRAINT BOARDS_READHIT_CK CHECK (READHIT >= 0);
ALTER TABLE BOARDS ADD CONSTRAINT BOARDS_MEMBERS_FK 
FOREIGN KEY (WRITER) REFERENCES MEMBERS(ID) ON DELETE SET NULL;

-- PRODUCTS 제약 조건
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_PK PRIMARY KEY (NUM);
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_STOCK_CK CHECK (STOCK >= 0);
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_PRICE_CK CHECK (PRICE >= 0);
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_CATEGORY_CK 
CHECK (CATEGORY IN ('bread','beverage','cake','macaron'));
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_POINT_CK CHECK (POINT >= 0);

-- ORDERS 제약 조건
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_PK PRIMARY KEY (OID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_MEMBERS_FK 
FOREIGN KEY (MID) REFERENCES MEMBERS(ID) ON DELETE SET NULL;

-- ORDERDETAILS 제약 조건
ALTER TABLE ORDERDETAILS ADD CONSTRAINT ORDERDETAILS_PK PRIMARY KEY (ODID);
ALTER TABLE ORDERDETAILS ADD CONSTRAINT ORDERDETAILS_ORDERS_FK 
FOREIGN KEY (OID) REFERENCES ORDERS(OID) ON DELETE CASCADE;
ALTER TABLE ORDERDETAILS ADD CONSTRAINT ORDERDETAILS_PRODUCTS_FK 
FOREIGN KEY (PNUM) REFERENCES PRODUCTS(NUM) ON DELETE SET NULL;


-- 시퀀스
CREATE SEQUENCE BOARD_SEQ;
CREATE SEQUENCE ORDERDETAIL_SEQ;
CREATE SEQUENCE ORDER_SEQ;
CREATE SEQUENCE PRODUCT_SEQ;