-- 테이블의 컬럼 정보 확인
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MEMBERS';


SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PRODUCTS';

-- 실습01. 컬럼 추가 (ADD COLUMN)
-- MEMBERS 테이블에 EMAIL 컬럼 추가
ALTER TABLE MEMBERS
ADD EMAIL VARCHAR2(100);

-- PRODUCTS 테이블에 숫자형 컬럼 DISCOUNT를 추가(기본 값 : 0)
ALTER TABLE PRODUCTS
ADD DISCOUNT NUMBER DEFAULT 0;

-- 실습02. 컬럼 수정 (MODIFY)
-- MEMBERS NAME 길이 변경
ALTER TABLE MEMBERS
MODIFY NAME VARCHAR2(50);

-- BOARDS.SUBJECT 컬럼의 길이를 100으로 설정해 보세요.
ALTER TABLE BOARDS
MODIFY SUBJECT VARCHAR2(100);

-- 실습03. 컬럼 이름 변경 (RENAME COLUMN)
-- MEMBERS ADDRESS → ADDR
ALTER TABLE MEMBERS
RENAME COLUMN ADDRESS TO ADDR;

-- PRODUCTS.CONTENT을 DESCRIPTION으로 이름 변경
ALTER TABLE PRODUCTS
RENAME COLUMN CONTENT TO DESCRIPTION;

-- 실습04. 컬럼 삭제 (DROP COLUMN)
-- MEMBERS MANAGER 컬럼 삭제
ALTER TABLE ORAMAN.MEMBERS
DROP COLUMN MANAGER;

-- PRODUCTS.IMAGE 컬럼을 삭제하세요.
ALTER TABLE PRODUCTS
DROP COLUMN IMAGE;

-- 실습05. 컬럼 기본값 변경
-- MEMBERS SALARY 기본값 변경
ALTER TABLE MEMBERS
MODIFY SALARY DEFAULT 1000;

-- BOARDS.READHIT의 기본 값을 10으로 변경하세요.
ALTER TABLE BOARDS
MODIFY READHIT DEFAULT 10;

-- 실습06. 컬럼 NOT NULL 제약 추가/제거
-- MEMBERS NAME NOT NULL 추가
ALTER TABLE MEMBERS
MODIFY NAME VARCHAR2(50) NOT NULL;

-- MEMBERS.NAME NOT NULL을 제거하세요.
ALTER TABLE MEMBERS
MODIFY NAME NULL;


-- 실습07. CHECK 제약 조건 추가/삭제
-- PRODUCTS DISCOUNT 0 이상 체크 추가
ALTER TABLE PRODUCTS
ADD CONSTRAINT PRODUCTS_DISCOUNT_CK CHECK (DISCOUNT >= 0);

-- CHECK 제약 조건 삭제
ALTER TABLE MEMBERS
DROP CONSTRAINT MEMBERS_PASSWORD_CK;

-- 실습08. FOREIGN KEY 실습 (추가 / 삭제)
-- ORDERS에 FK 다시 추가
ALTER TABLE ORDERS
ADD CONSTRAINT ORDERS_MEMBERS_FK2
FOREIGN KEY (MID) REFERENCES MEMBERS(ID);

-- FK 삭제
ALTER TABLE ORDERS
DROP CONSTRAINT ORDERS_MEMBERS_FK2;

-- 실습09. 컬럼 포함 데이터 테스트 (중요)
-- 정상 데이터
INSERT INTO MEMBERS (ID, NAME, PASSWORD, GENDER, SALARY)
VALUES ('user1', '홍길동', '1234', '남자', 200);

-- 오류 발생 (GENDER 체크 위반)
INSERT INTO MEMBERS (ID, NAME, PASSWORD, GENDER, SALARY)
VALUES ('user2', '김철수', '1234', '중성', 200);

-- 오류 발생 (SALARY 체크 위반)
INSERT INTO MEMBERS (ID, NAME, PASSWORD, GENDER, SALARY)
VALUES ('user3', '이영희', '1234', '여자', 50);

-- 실습10. FK 삭제 불가 상황 테스트 (핵심 실습)
-- 부모 테이블 삭제 시도 (실패)
DROP TABLE MEMBERS;

-- 해결 방법 1 (CASCADE)
DROP TABLE MEMBERS CASCADE CONSTRAINTS;

-- 해결 방법 2 (자식 먼저 삭제)
DROP TABLE ORDERDETAILS;
DROP TABLE ORDERS;
DROP TABLE BOARDS;
DROP TABLE MEMBERS;